### PR TITLE
server: wrap the default server.now function to always return UTC

### PR DESCRIPTION
**Pull request by jwmaag**
This change was my resolution to the issue described in #745

### CODE REVIEW

**Comment by ericchiang** [comment]
This is a small fix but isn't the real solution to store the timestamps in postgres?

**Comment by ericchiang** [comment]
Sorry, I mean storing timezones.

**Comment by jwmaag** [comment]
Right, You could migrate the database to timestamptz, but it seemed simpler to just take timezone out of the equation all together.

does the sqlite backend take the timestamp column as is?

**Comment by ericchiang** [comment]
> Right, You could migrate the database to timestamptz, but it seemed simpler to just take timezone out of the equation all together.

It'd be quicker to switch everything over to UTC, but I'd rather the server not be dependent on us never using timezones. E.g. it's weird for logs to spit out timestamps in two different timezones (one for the logging metadata, another for the printed time). I think it should be a quick enough fix.

In terms of migrations I don't even know if this one is safe. If the server's been storing timestamps in one format then suddenly switches a few hours ahead or behind that's going to have some really bad consequences I think the fix for this might have to be breaking.  

> does the sqlite backend take the timestamp column as is?

Yes, we have to investigate if that's an issue.

**Comment by jwmaag** [comment]
Agree that shoehorning something globally to fix a storage backend issue is probably not the correct solution. Closing.

**Pull request closed without merging**
