### PR TITLE
server: fix key rotation polling

### LINKED ISSUE #619: server: key rotation polling wait is wrong
If keys rotate every 24 hours and the server fails to create the initial key it will wait 24 hours to re-poll.[0] This is bad and requires occasionally destroying dex in order to re-sync the keys properly.

Change this to poll at a predefined interval. Say 30 seconds.

cc @dghubble 

[0] https://github.com/coreos/dex/blob/3e94e65b68097c057331381fd0434055a4949c3e/server/rotation.go#L79

### PR DESCRIPTION
**Pull request by ericchiang**
fixes #619

cc @dghubble

### CODE REVIEW

**Comment by dghubble** [comment]
What as the `strategy.period` and why not set it?

**Comment by ericchiang** [comment]
How long the key are valid for. Used to set the next expiry[0].

Let me give that a better name. Maybe `keysValidFor`

[0] https://github.com/ericchiang/dex/blob/d8033999d56d9600f431e76bc50831108c920b7a/server/rotation.go#L148

**Comment by dghubble** [comment]
Oh, that is kinda unclear. Maybe `rotatePeriod` or `rotateDuration`? If we're being pedantic, frequency isn't the right name.

**Comment by ericchiang** [comment]
I don't want to be pedantic.

**Comment by dghubble** [comment]
:+1:

**Pull request merged**
