### PR TITLE
connector_oauth2.go: use embedded HTTPClient

### LINKED ISSUE #395: connectors: allow for retrieving OAuth2 client
Given an OAuth2 connector (much like the github connector) to an OAuth2 service _that doesn't use proper TLS certificates_ (self-signed or a CA not trusted by the system cert pool), you might have the following bits in the connector config:

```go
type MyConnectorConfig struct {
	ID           string `json:"id"`
	ClientID     string `json:"clientID"`
	ClientSecret string `json:"clientSecret"`
	URL      string `json:"URL"`
	Cert     string `json:"cert"`
	SkipVerify   bool   `json:"insecureSkipVerify"`
}
```

accompanied by

```go
func newMyConnector(clientID, clientSecret, url, cert string, skipVerify bool, cbURL string) (oauth2Connector, error) {
	config := oauth2.Config{
		Credentials: oauth2.ClientCredentials{ID: clientID, Secret: clientSecret},
		AuthURL:     url + myAuthPath,
		TokenURL:    url + myTokenPath,
		RedirectURL: cbURL,
	}

	var client *http.Client
	if chefCert != "" {
		caPool := x509.NewCertPool()
		caPool.AppendCertsFromPEM([]byte(cert))
		tlsConfig := &tls.Config{
			RootCAs: caPool,
		}

		tr := &http.Transport{TLSClientConfig: tlsConfig}
		client = &http.Client{Transport: tr}
	} else if skipVerify {
		tr := &http.Transport{TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		}}
		client = &http.Client{Transport: tr}
	} else {
		client = http.DefaultClient
	}

	cli, err := oauth2.NewClient(client, config)
	if err != nil {
		return nil, err
	}

	return &myOAuth2Connector{
		clientID:     clientID,
		clientSecret: clientSecret,
		client:       cli,
		url:      url,
	}, nil
}
```

This will work fine _until_  the callback handler uses `http.DefaultClient` again [_here_](https://github.com/coreos/dex/blob/master/connector/connector_oauth2.go#L87):

```go
		ident, err := c.conn.Identity(newAuthenticatedClient(token, http.DefaultClient))
		if err != nil {
			log.Errorf("Unable to retrieve identity: %v", err)
```

...at which point TLS verification fails.

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #395.

(While I tend to agree with https://github.com/coreos/dex/issues/395#issuecomment-209215114, this seems to be the least intrusive way to get to where I want...)

Curious if this works on Travis, because locally I seem to have botched up something around the dependencies...

### CODE REVIEW

**Comment by ericchiang** [comment]
Please see our documentation on updating vendored dependencies: https://github.com/coreos/dex/blob/master/Documentation/dev-guide.md#updating-an-existing-package

**Comment by ericchiang** [comment]
Note that we recently switched to https://github.com/Masterminds/glide. I apologize if you've already familiarized yourself with godep, but we've had major issues with it in the past.

**Comment by srenatus** [comment]
Oooh I hadn't noticed that, sorry. I'll update this, of course.

**Comment by srenatus** [comment]
Hmm this would fix #353, too, but without having fixed the tests :confused: 
And https://github.com/coreos/dex/pull/353/commits/dafdfc978681d3e790db205a2f8f02c081af9241 doesn't really solve all problems yet, so... I guess I'll just hold this one until #353 is done with? 

@fnordahl: are you still on it? Feel free to pick c0c46f0 to shortcut the glide-based dependency update, I'll just rework this branch afterwards. :)

**Comment by ericchiang** [comment]
@srenatus we removed a couple fields from the `oidc/http` subpackage to prevent normal packages from importing `net/http/httptest` https://github.com/coreos/go-oidc/pull/59. This will require updating some of dex's code to account for these missing fields.

I'll try to do that update in the near future if you don't get to it first.

Otherwise, please see my comment here https://github.com/coreos/dex/issues/395#issuecomment-209215114. That would be a fix you can do without pulling in your change to coreos/go-oidc, and in my opinion is the preferred fix.

**Comment by fnordahl** [comment]
@srenatus I still have an intention to get #353 in. I have not chased down or solved how ti fix the remaining issues yet though. I will try to re-iterate and see if I can come up with a sollution soon.

**Comment by srenatus** [comment]
@ericchiang ok, I'll just update this in accordance with https://github.com/coreos/dex/issues/395#issuecomment-209215114 then

@fnordahl ok, thanks!

**Comment by srenatus** [comment]
Didn't keep my promise... sorry! It's obsolete now, I suppose, gc'ing.

**Pull request closed without merging**
