### PR TITLE
Fix a tyop in the storage documentation

### PR DESCRIPTION
**Pull request by SEJeff**
Found while reading the docs

### CODE REVIEW

**Comment by ericchiang** [comment]
`README` -> `Documentation/storage.md`?

**Comment by SEJeff** [comment]
@ericchiang better? ^^

**Comment by ericchiang** [comment]
Typo in your commit message. Also we generally prefix the commit message with the directory. So it would be

```
Documentation: fix a typo in the storage documentation
```

That okay?

**Comment by SEJeff** [comment]
@ericchiang yes, the commit message is misspelled on purpose. It was sarcasm. I'll fix it since you don't appreciate the humour. Just a moment please.

**Comment by SEJeff** [comment]
Hopefully that looks better. I'll try to do a better job the next time I contribute to CoreOS Inc. projects.

**Comment by ericchiang** [comment]
Ah sorry. Those kinds of jokes are hard over the internet. Thanks for the fix!

**Pull request merged**
