### PR TITLE
api: add gRPC calls to create, list and delete connectors.

### PR DESCRIPTION
**Pull request by rithujohn191**
This change defines 4 new API calls: 
* CreateConnector
* UpdateConnector
* ListConnectors
* DeleteConnector

Also added unit tests for each.

### CODE REVIEW

**Comment by rithujohn191** [comment]
Added the following changes:
* Added static storage support. The idea is that the connectors that are in the Dex ConfigMap will be treated as static resources which cannot be modified in anyway.
* The server list of connectors must have both static connectors and regular storage connectors (which can be manipulated via API calls)
* Unit tests to test static connector behavior.

I have not changes out the server struct to have connectors of type Storage.Connector yet. Let me know if you would still like me to make that switch.

**Comment by ericchiang** [comment]
FYI this still needs to have the server dynamically query the storage when listing connectors (e.g. for the login page) or when a user hits a specific connector.

I think that's a prerequisite for adding these API calls, because without that, the API calls don't do anything until you restart the server.

**Comment by rithujohn191** [comment]
Yes. Working on those changes now.

**Comment by rithujohn191** [comment]
#913 is a pre-req for this PR

**Comment by rithujohn191** [comment]
Breaking this up into smaller PRs

**Pull request closed without merging**
