### PR TITLE
Add TLS support to the example application

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes issue #450.

Added two flags for passing the cert and key files. If both flags are set, the server is started using TLS.

### CODE REVIEW

**Comment by ericchiang** [comment]
This is going to be tricky since "--listen" and "--callback-url" defaults are "http://".

Can we add some UX to make sure someone specifying these flags also uses the correct scheme for appropriate flags?

**Comment by alexbrand** [comment]
@ericchiang Good call. I'll try to work on this tonight.

**Comment by ericchiang** [comment]
Awesome. A simple solution would be to ensure that the scheme matches the type of listener, and error out if they don't match.

**Comment by alexbrand** [comment]
Looks like I messed up the rebase? :-(

**Comment by ericchiang** [comment]
Yep :(

Don't know how much I can help.

**Comment by alexbrand** [comment]
I'll create a new PR with a proper branch.

**Pull request closed without merging**
