### PR TITLE
Require the connector to have an ID.

### PR DESCRIPTION
**Pull request by cjyar**

### CODE REVIEW

**Comment by ericchiang** [comment]
```
cmd/dex/serve.go:116: invalid operation: conn.ID == nil (mismatched types string and nil)
```

**Comment by ericchiang** [comment]
Thanks for the PR! ID is a string so you'll have to do `conn.ID == ""`

Updates #681

**Comment by cjyar** [comment]
D'oh! I guess it helps to make sure the code compiles before I send a PR.

**Comment by ericchiang** [comment]
@cjyar that's why we have CI :)

**Comment by ericchiang** [comment]
@cjyar can you squash and edit the commit message to begin with `cmd/dex`. That's just a CoreOS style thing. For example

```
cmd/dex: validate that connectors have an ID
```

**Comment by cjyar** [comment]
@ericchiang It won't let me. I can squash them in my repo, delete this PR, and make a new one. Or you can squash them on your end with the pulldown on the "Merge pull request" button. That button doesn't show up for me, because I don't have permission to merge into your repo.

**Comment by SEJeff** [comment]
@cjyar You can squash them locally on your workstation and force push to the `master` branch on your fork under @cjyar. That will then update this PR with a squashed version with the requested changes.

**Comment by cjyar** [comment]
@SEJeff Thanks for the tip!

**Comment by ericchiang** [comment]
lgtm!

**Pull request merged**
