### PR TITLE
Documentation: OIDC conformance test setup

### PR DESCRIPTION
**Pull request by estroz**
Document setting up a dex test server and OpenID test instance to test dex against the OpenID Connect Basic OP ([profile outline](http://openid.net/wordpress-content/uploads/2016/12/OpenID-Connect-Conformance-Profiles.pdf), section 2.1.1) test profile.

Relates to #42

### CODE REVIEW

**Comment by rithujohn191** [comment]
Once Dex actually passes all the conformance tests we can get this doc in.

**Comment by ericchiang** [comment]
> Once Dex actually passes all the conformance tests we can get this doc in.

I disagree. I think it'd be useful for us to document how to run the conformance tests in order to make dex conform to it.

**Comment by rithujohn191** [comment]
Ok then this document needs to be re-worded to reflect that. It has to be clear that these are just instructions and we do not fully comply as of yet

**Comment by estroz** [comment]
@rithujohn191 @ericchiang added some sweet tables and noted that dex is not yet compliant

**Pull request merged**
