### PR TITLE
add dynamic client registration

### PR DESCRIPTION
**Pull request by ericchiang**
Update go-oidc to include coreos/go-oidc#38.

This PR provides the necessary changes to field names, changes to types, and adds a database migration to accommodate the changes in JSON marshaling for oidc.ClientMetadata.

### CODE REVIEW

**Comment by ericchiang** [comment]
I want to address #268 and cut a security release before adding this commit since we only track oe  branch and it's too significant a change for a minor release.

**Comment by ericchiang** [comment]
@bobbyrullo just realized that this change might break dex's [user API](https://github.com/coreos/dex/blob/b5c7f1978e0718d9631e512c385eb0dea99b732d/schema/workerschema/v1.json#L36-L51) since it alters the marshaling tags.

**Comment by ericchiang** [comment]
TODO:

- [ ] Add a `disabled` flag to the client structure in the database and GET /clients APIs
- [ ] Add POST /clients/{id}/disable call to API
- [ ] Update worker API to include additional fields added to client and client response fields

**Comment by bobbyrullo** [comment]
mostly good, couple of minor fixes.

**Comment by bobbyrullo** [comment]
LGTM, after that one tiny change.

**Pull request merged**
