### PR TITLE
add basic auth url decode

### PR DESCRIPTION
**Pull request by gerson24**
Now it follows oauth2 spec(http://tools.ietf.org/html/rfc6749#section-2.3.1).

Fixes: #336

### CODE REVIEW

**Comment by ericchiang** [comment]
As discussed in #336 we'd like to have this try both decodings for a little bit (at least for one release) for backward compatibility issues. Can you update your patch to try the correct encoding, and if that doesn't work, try the old one?

**Comment by gerson24** [comment]
Check it now, if you want I can to move this: https://github.com/coreos/dex/blob/master/server/server.go#L413-L422 to http.go and fix the testing in both files

**Comment by gerson24** [comment]
Ok! I'm working on test file

**Comment by ericchiang** [comment]
@gerson24 we're hoping to push a 0.3.0 release today and would very much like to see this in there. Would it be okay to merge as is then add tests in another pr?

**Comment by adrianlop** [comment]
yep, we can do that! thanks @ericchiang

**Comment by ericchiang** [comment]
For last yesterday's release we had a change of heart and pushed the original fix (see #357). Apologies for pushing that ourselves, we were on a tight schedule. Thank you for reporting the issue originally and your work in this PR.

Closing this one since the fix is now in master.

**Pull request closed without merging**
