### PR TITLE
travis: Change from after_success script to travis deploy

### PR DESCRIPTION
**Pull request by dghubble**
Travis has a nicer `deploy` construct which has builtin support for conditioning on branches, language versions, tags, conditions, etc. I think this should work the same for you.

* https://docs.travis-ci.com/user/deployment/script
* https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

Fixed spacing to consistently use 2 spaces instead of a blend of 1 and 2.

### CODE REVIEW

**Comment by ericchiang** [comment]
LGTM

**Comment by ericchiang** [comment]
@dghubble fyi this has broken the build: https://travis-ci.org/coreos/dex/jobs/103429418

**Comment by dghubble** [comment]
@ericchiang hm, the deploy section is identical to (working) https://github.com/coreos/coreos-baremetal/blob/master/.travis.yml except for the script name

**Comment by dghubble** [comment]
Well, this [tweak](https://github.com/coreos/dex/commit/ef5ae4e3ba8f0e78462816461f3fe110c2990a68) with a quoted script name [succeeds](https://travis-ci.org/coreos/dex/jobs/103552312) up until the Docker push (commented out) on a test branch. So either the push was failing before or quoting scripts which reside in the cwd is important.

Possible fix https://github.com/coreos/dex/pull/283, not sure if there is a better way to dry-run Travis verbosely.

**Pull request merged**
