### PR TITLE
Themes plus css refactor

### PR DESCRIPTION
**Pull request by amrutac**
Screenshots and PR comments in https://github.com/coreos/dex/pull/714.

### CODE REVIEW

**Comment by ericchiang** [comment]
cc @sym3tri

**Comment by ericchiang** [comment]
fyi @rithujohn191 the tectonic theme can be enabled by adding the following config entry

```
frontend:
    theme: tectonic
```

**Comment by amrutac** [comment]
@sym3tri: Cleaned up svgs, and moved the <code>btn-provider</code> class to themes. I can't set up a svg logo for coreos cause the image type(png) is hardcoded for the logo in the code.

**Comment by ericchiang** [comment]
@sym3tri going to wait for your lgtm

**Comment by sym3tri** [comment]
I see. LGTM.

**Pull request merged**
