### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by ericchiang**
Would like to get #202 and #210 merged before releasing. Also probably need to change some of the build scripts to use a version rather than a git SHA.

Is there anything else we want to wait for?

### CODE REVIEW

**Comment by bcwaldon** [comment]
@ericchiang thanks for writing these notes up, but we use GitHub releases and git tags to manage our release process. When we are ready to cut the release, we will cut a signed tag and use your changelog as the start of the release notes.

**Comment by ericchiang** [comment]
@bcwaldon thanks. Realize now this PR should probably just be "added changelog".

Was planning on doing a proper github release once this got in :smile:

**Comment by bcwaldon** [comment]
@ericchiang We use the GitHub release history as the de facto changelog, so I don't think this is necessary.

**Comment by ericchiang** [comment]
@bcwaldon ah, okay.

**Pull request closed without merging**
