### PR TITLE
Documentation: clearer guidance on creating OAuth 2 client ID

### LINKED ISSUE #125: Documentation: specify where API keys are created in Google Developer Console
The getting started guide presently says 'Click on Credentials' without specifying that it's part of the APIs and auth menu

### PR DESCRIPTION
**Pull request by cpswan**
Provides a more accurate walk through of the screens and menus of the Google
Developers Console encountered whilst creating a client ID.

Fixes #125

Signed-off-by: Chris Swan <@cpswan>

### CODE REVIEW

**Comment by cpswan** [comment]
The point is that you need to make a note of the secret key (because it will vanish from the Google Developers Console screen, but you'll need it later), and if we're telling people to make a note of a secret then that secret *should* be put into a sensible place. If they then put it into a public gist then that's their problem.

**Comment by cpswan** [comment]
Changes made to suggested Google credential handling in line with @bobbyrullo suggestion

**Comment by bobbyrullo** [comment]
LGTM - just fix your conflicts. Thank you!

**Comment by cpswan** [comment]
Conflict fixed. To be honest I was't clear what to do about two separate PRs on the same file (and it seemed rude to assume that the first would be merged and to thus make it part of the second).

**Comment by bobbyrullo** [comment]
hey sorry for the delay - but can you squash into one commit?

**Comment by cpswan** [comment]
@bobbyrullo now squashed

**Comment by bobbyrullo** [comment]
Thanks @cpswan

**Pull request merged**
